# Generated by Django 4.0.4 on 2022-07-11 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_alter_store_description_alter_store_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated'), ('in_review', 'In Review')], default='in_review', max_length=11),
        ),
    ]
