# Generated by Django 4.0.4 on 2022-07-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_store_options_store_owner_store_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('in_review', 'In Review'), ('active', 'Active'), ('deactivated', 'Deactivated')], default='in_review', max_length=11),
        ),
    ]
