# Generated by Django 4.0.4 on 2022-07-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_store_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-id']},
        ),
    ]
